/* Auto-generated from https://t3themes.com (SunkenInTime/t3-themes). Do not edit by hand.
 * Regenerate: node scripts/gen-t3-themes.mjs
 */
export type ThemeAppearance = "dark" | "light";

export type ThemeAnsi = {
  black: string;
  red: string;
  green: string;
  yellow: string;
  blue: string;
  magenta: string;
  cyan: string;
  white: string;
  brightBlack: string;
  brightRed: string;
  brightGreen: string;
  brightYellow: string;
  brightBlue: string;
  brightMagenta: string;
  brightCyan: string;
  brightWhite: string;
};

export type ThemeTokens = {
  appearance: ThemeAppearance;
  bg: string;
  bgRaised: string;
  bgHover: string;
  surface: string;
  border: string;
  borderStrong: string;
  text: string;
  muted: string;
  accent: string;
  onAccent: string;
  accent2: string;
  accentSoft: string;
  attention: string;
  attentionRing: string;
  ok: string;
  danger: string;
  termBg: string;
  termFg: string;
  termCursor: string;
  termSelection: string;
  termChrome: string;
  termChromeText: string;
  termChromeMuted: string;
  preview: [string, string, string, string];
};

export type ThemeDefinition = {
  id: string;
  familyId: string;
  label: string;
  official: boolean;
  appearance: ThemeAppearance;
  tokens: ThemeTokens;
  ansi: ThemeAnsi;
};

export const THEME_CATALOG: ThemeDefinition[] = [
  {
    "id": "voxiva",
    "familyId": "voxiva",
    "label": "Voxiva",
    "official": true,
    "appearance": "dark",
    "tokens": {
      "appearance": "dark",
      "bg": "#07090e",
      "bgRaised": "#0c1119",
      "bgHover": "#151c28",
      "surface": "#101722",
      "border": "rgba(255,255,255,0.055)",
      "borderStrong": "rgba(255,255,255,0.11)",
      "text": "#eef2f8",
      "muted": "#8a93a8",
      "accent": "#5aa6ff",
      "onAccent": "#031018",
      "accent2": "#7ad7ff",
      "accentSoft": "rgba(90,166,255,0.14)",
      "attention": "#efc35a",
      "attentionRing": "rgba(239,195,90,0.35)",
      "ok": "#3fd49a",
      "danger": "#ff7b7b",
      "termBg": "#0c1119",
      "termFg": "#e8ecf4",
      "termCursor": "#5aa6ff",
      "termSelection": "#5aa6ff44",
      "termChrome": "#0c1119",
      "termChromeText": "#eef2f8",
      "termChromeMuted": "#8a93a8",
      "preview": [
        "#080a0f",
        "#10151e",
        "#4d9dff",
        "#e9edf5"
      ]
    },
    "ansi": {
      "black": "#0c1119",
      "red": "#ff7b7b",
      "green": "#3fd49a",
      "yellow": "#efc35a",
      "blue": "#5aa6ff",
      "magenta": "#c792ea",
      "cyan": "#7ad7ff",
      "white": "#e8ecf4",
      "brightBlack": "#6b7385",
      "brightRed": "#ff9b9b",
      "brightGreen": "#6ee7b7",
      "brightYellow": "#f5d78e",
      "brightBlue": "#8bbcff",
      "brightMagenta": "#d7a8ff",
      "brightCyan": "#a6e8ff",
      "brightWhite": "#ffffff"
    }
  },
  {
    "id": "apple-frost",
    "familyId": "apple-frost",
    "label": "Apple Frost",
    "official": false,
    "appearance": "light",
    "tokens": {
      "appearance": "light",
      "bg": "#f5f5f7",
      "bgRaised": "#f4f8fb",
      "bgHover": "#e6e6ea",
      "surface": "#ffffff",
      "border": "#d2d2d761",
      "borderStrong": "#d2d2d794",
      "text": "#1d1d1f",
      "muted": "#6e6e73",
      "accent": "#0071e3",
      "onAccent": "#ffffff",
      "accent2": "#0066cc",
      "accentSoft": "#0071e329",
      "attention": "#b25000",
      "attentionRing": "#b250004d",
      "ok": "#0066cc",
      "danger": "#d70015",
      "termBg": "#1d1d1f",
      "termFg": "#f4f8fb",
      "termCursor": "#2997ff",
      "termSelection": "#33507a",
      "termChrome": "#ffffff",
      "termChromeText": "#1d1d1f",
      "termChromeMuted": "#6a6a6f",
      "preview": [
        "#f5f5f7",
        "#ffffff",
        "#0071e3",
        "#1d1d1f"
      ]
    },
    "ansi": {
      "black": "#1d1d1f",
      "red": "#d70015",
      "green": "#0066cc",
      "yellow": "#b25000",
      "blue": "#0071e3",
      "magenta": "#0066cc",
      "cyan": "#0066cc",
      "white": "#f4f8fb",
      "brightBlack": "#6e6e73",
      "brightRed": "#d70015",
      "brightGreen": "#0066cc",
      "brightYellow": "#b25000",
      "brightBlue": "#0071e3",
      "brightMagenta": "#0066cc",
      "brightCyan": "#0066cc",
      "brightWhite": "#020617"
    }
  },
  {
    "id": "apple-frost-dark",
    "familyId": "apple-frost",
    "label": "Apple Frost",
    "official": false,
    "appearance": "dark",
    "tokens": {
      "appearance": "dark",
      "bg": "#000000",
      "bgRaised": "#252527",
      "bgHover": "#1d1d1f",
      "surface": "#1d1d1f",
      "border": "#33333324",
      "borderStrong": "#3333333d",
      "text": "#f5f5f7",
      "muted": "#8e8e93",
      "accent": "#0a84ff",
      "onAccent": "#ffffff",
      "accent2": "#2997ff",
      "accentSoft": "#0a84ff29",
      "attention": "#ff9f0a",
      "attentionRing": "#ff9f0a4d",
      "ok": "#2997ff",
      "danger": "#ff453a",
      "termBg": "#000000",
      "termFg": "#f4f8fb",
      "termCursor": "#2997ff",
      "termSelection": "#1f3c5c",
      "termChrome": "#0a0a0b",
      "termChromeText": "#f5f5f7",
      "termChromeMuted": "#98989d",
      "preview": [
        "#000000",
        "#1d1d1f",
        "#0a84ff",
        "#f5f5f7"
      ]
    },
    "ansi": {
      "black": "#000000",
      "red": "#ff453a",
      "green": "#2997ff",
      "yellow": "#ff9f0a",
      "blue": "#0a84ff",
      "magenta": "#2997ff",
      "cyan": "#2997ff",
      "white": "#f4f8fb",
      "brightBlack": "#8e8e93",
      "brightRed": "#ff453a",
      "brightGreen": "#2997ff",
      "brightYellow": "#ff9f0a",
      "brightBlue": "#0a84ff",
      "brightMagenta": "#2997ff",
      "brightCyan": "#2997ff",
      "brightWhite": "#ffffff"
    }
  },
  {
    "id": "espresso",
    "familyId": "espresso",
    "label": "Espresso",
    "official": false,
    "appearance": "dark",
    "tokens": {
      "appearance": "dark",
      "bg": "#241c17",
      "bgRaised": "#332921",
      "bgHover": "#3c3129",
      "surface": "#2c231d",
      "border": "#3c312924",
      "borderStrong": "#3c31293d",
      "text": "#e8dcd0",
      "muted": "#b3a191",
      "accent": "#c58d5f",
      "onAccent": "#ffffff",
      "accent2": "#c58d5f",
      "accentSoft": "#c58d5f29",
      "attention": "#efc35a",
      "attentionRing": "#efc35a4d",
      "ok": "#07090e",
      "danger": "#ff7b7b",
      "termBg": "#201913",
      "termFg": "#e8dcd0",
      "termCursor": "#c58d5f",
      "termSelection": "#443729",
      "termChrome": "#241c17",
      "termChromeText": "#e8dcd0",
      "termChromeMuted": "#a7947f",
      "preview": [
        "#241c17",
        "#2c231d",
        "#c58d5f",
        "#e8dcd0"
      ]
    },
    "ansi": {
      "black": "#201913",
      "red": "#ff7b7b",
      "green": "#07090e",
      "yellow": "#efc35a",
      "blue": "#c58d5f",
      "magenta": "#c58d5f",
      "cyan": "#c58d5f",
      "white": "#e8dcd0",
      "brightBlack": "#b3a191",
      "brightRed": "#ff7b7b",
      "brightGreen": "#07090e",
      "brightYellow": "#efc35a",
      "brightBlue": "#c58d5f",
      "brightMagenta": "#c58d5f",
      "brightCyan": "#c58d5f",
      "brightWhite": "#ffffff"
    }
  },
  {
    "id": "espresso-light",
    "familyId": "espresso",
    "label": "Espresso",
    "official": false,
    "appearance": "light",
    "tokens": {
      "appearance": "light",
      "bg": "#f3ede4",
      "bgRaised": "#f8f3ea",
      "bgHover": "#ddd2c2",
      "surface": "#ece4d8",
      "border": "#ddd2c261",
      "borderStrong": "#ddd2c294",
      "text": "#3b2f2a",
      "muted": "#7c6a5d",
      "accent": "#8c5a3c",
      "onAccent": "#ffffff",
      "accent2": "#07090e",
      "accentSoft": "#8c5a3c29",
      "attention": "#efc35a",
      "attentionRing": "#efc35a4d",
      "ok": "#07090e",
      "danger": "#ff7b7b",
      "termBg": "#f3ede4",
      "termFg": "#3b2f2a",
      "termCursor": "#8c5a3c",
      "termSelection": "#d9cab3",
      "termChrome": "#f3ede4",
      "termChromeText": "#3b2f2a",
      "termChromeMuted": "#7c6a5d",
      "preview": [
        "#f3ede4",
        "#ece4d8",
        "#8c5a3c",
        "#3b2f2a"
      ]
    },
    "ansi": {
      "black": "#f3ede4",
      "red": "#ff7b7b",
      "green": "#07090e",
      "yellow": "#efc35a",
      "blue": "#8c5a3c",
      "magenta": "#07090e",
      "cyan": "#07090e",
      "white": "#3b2f2a",
      "brightBlack": "#7c6a5d",
      "brightRed": "#ff7b7b",
      "brightGreen": "#07090e",
      "brightYellow": "#efc35a",
      "brightBlue": "#8c5a3c",
      "brightMagenta": "#07090e",
      "brightCyan": "#07090e",
      "brightWhite": "#020617"
    }
  },
  {
    "id": "fjord",
    "familyId": "fjord",
    "label": "Fjord",
    "official": false,
    "appearance": "light",
    "tokens": {
      "appearance": "light",
      "bg": "#eceff4",
      "bgRaised": "#f2f4f8",
      "bgHover": "#d8dee9",
      "surface": "#e5e9f0",
      "border": "#d8dee961",
      "borderStrong": "#d8dee994",
      "text": "#2e3440",
      "muted": "#5e6a7e",
      "accent": "#5e81ac",
      "onAccent": "#ffffff",
      "accent2": "#07090e",
      "accentSoft": "#5e81ac29",
      "attention": "#efc35a",
      "attentionRing": "#efc35a4d",
      "ok": "#07090e",
      "danger": "#ff7b7b",
      "termBg": "#eceff4",
      "termFg": "#2e3440",
      "termCursor": "#5e81ac",
      "termSelection": "#cdd5e0",
      "termChrome": "#eceff4",
      "termChromeText": "#2e3440",
      "termChromeMuted": "#5e6a7e",
      "preview": [
        "#eceff4",
        "#e5e9f0",
        "#5e81ac",
        "#2e3440"
      ]
    },
    "ansi": {
      "black": "#eceff4",
      "red": "#ff7b7b",
      "green": "#07090e",
      "yellow": "#efc35a",
      "blue": "#5e81ac",
      "magenta": "#07090e",
      "cyan": "#07090e",
      "white": "#2e3440",
      "brightBlack": "#5e6a7e",
      "brightRed": "#ff7b7b",
      "brightGreen": "#07090e",
      "brightYellow": "#efc35a",
      "brightBlue": "#5e81ac",
      "brightMagenta": "#07090e",
      "brightCyan": "#07090e",
      "brightWhite": "#020617"
    }
  },
  {
    "id": "fjord-dark",
    "familyId": "fjord",
    "label": "Fjord",
    "official": false,
    "appearance": "dark",
    "tokens": {
      "appearance": "dark",
      "bg": "#2e3440",
      "bgRaised": "#3b4252",
      "bgHover": "#434c5e",
      "surface": "#353c4a",
      "border": "#434c5e24",
      "borderStrong": "#434c5e3d",
      "text": "#eceff4",
      "muted": "#a3aec2",
      "accent": "#88c0d0",
      "onAccent": "#2e3440",
      "accent2": "#88c0d0",
      "accentSoft": "#88c0d029",
      "attention": "#efc35a",
      "attentionRing": "#efc35a4d",
      "ok": "#07090e",
      "danger": "#ff7b7b",
      "termBg": "#2b303b",
      "termFg": "#eceff4",
      "termCursor": "#88c0d0",
      "termSelection": "#434c5e",
      "termChrome": "#2e3440",
      "termChromeText": "#eceff4",
      "termChromeMuted": "#9aa5ba",
      "preview": [
        "#2e3440",
        "#353c4a",
        "#88c0d0",
        "#eceff4"
      ]
    },
    "ansi": {
      "black": "#2b303b",
      "red": "#ff7b7b",
      "green": "#07090e",
      "yellow": "#efc35a",
      "blue": "#88c0d0",
      "magenta": "#88c0d0",
      "cyan": "#88c0d0",
      "white": "#eceff4",
      "brightBlack": "#a3aec2",
      "brightRed": "#ff7b7b",
      "brightGreen": "#07090e",
      "brightYellow": "#efc35a",
      "brightBlue": "#88c0d0",
      "brightMagenta": "#88c0d0",
      "brightCyan": "#88c0d0",
      "brightWhite": "#ffffff"
    }
  },
  {
    "id": "miami-nights",
    "familyId": "miami-nights",
    "label": "Miami Nights",
    "official": false,
    "appearance": "dark",
    "tokens": {
      "appearance": "dark",
      "bg": "#17102b",
      "bgRaised": "#241a44",
      "bgHover": "#2c2050",
      "surface": "#1e1538",
      "border": "#2c205024",
      "borderStrong": "#2c20503d",
      "text": "#f3e9ff",
      "muted": "#a78fc9",
      "accent": "#ff5fa2",
      "onAccent": "#ffffff",
      "accent2": "#3be8f0",
      "accentSoft": "#ff5fa229",
      "attention": "#ffb454",
      "attentionRing": "#ffb4544d",
      "ok": "#07090e",
      "danger": "#ff4d6d",
      "termBg": "#120c22",
      "termFg": "#e8dcff",
      "termCursor": "#ff5fa2",
      "termSelection": "#33245e",
      "termChrome": "#17102b",
      "termChromeText": "#f3e9ff",
      "termChromeMuted": "#9a82be",
      "preview": [
        "#17102b",
        "#1e1538",
        "#ff5fa2",
        "#f3e9ff"
      ]
    },
    "ansi": {
      "black": "#120c22",
      "red": "#ff4d6d",
      "green": "#07090e",
      "yellow": "#ffb454",
      "blue": "#ff5fa2",
      "magenta": "#3be8f0",
      "cyan": "#3be8f0",
      "white": "#e8dcff",
      "brightBlack": "#a78fc9",
      "brightRed": "#ff4d6d",
      "brightGreen": "#07090e",
      "brightYellow": "#ffb454",
      "brightBlue": "#ff5fa2",
      "brightMagenta": "#3be8f0",
      "brightCyan": "#3be8f0",
      "brightWhite": "#ffffff"
    }
  },
  {
    "id": "midnight-harbor",
    "familyId": "midnight-harbor",
    "label": "Midnight Harbor",
    "official": false,
    "appearance": "dark",
    "tokens": {
      "appearance": "dark",
      "bg": "#0b0e14",
      "bgRaised": "#1a2029",
      "bgHover": "#1a2029",
      "surface": "#151a23",
      "border": "#232a3624",
      "borderStrong": "#232a363d",
      "text": "#d6dce6",
      "muted": "#8a94a6",
      "accent": "#7aa2f7",
      "onAccent": "#ffffff",
      "accent2": "#7aa2f7",
      "accentSoft": "#7aa2f729",
      "attention": "#efc35a",
      "attentionRing": "#efc35a4d",
      "ok": "#07090e",
      "danger": "#ff7b7b",
      "termBg": "#0b0e14",
      "termFg": "#d6dce6",
      "termCursor": "#7aa2f7",
      "termSelection": "#28324a",
      "termChrome": "#0b0e14",
      "termChromeText": "#d6dce6",
      "termChromeMuted": "#8a94a6",
      "preview": [
        "#0b0e14",
        "#151a23",
        "#7aa2f7",
        "#d6dce6"
      ]
    },
    "ansi": {
      "black": "#0b0e14",
      "red": "#ff7b7b",
      "green": "#07090e",
      "yellow": "#efc35a",
      "blue": "#7aa2f7",
      "magenta": "#7aa2f7",
      "cyan": "#7aa2f7",
      "white": "#d6dce6",
      "brightBlack": "#8a94a6",
      "brightRed": "#ff7b7b",
      "brightGreen": "#07090e",
      "brightYellow": "#efc35a",
      "brightBlue": "#7aa2f7",
      "brightMagenta": "#7aa2f7",
      "brightCyan": "#7aa2f7",
      "brightWhite": "#ffffff"
    }
  },
  {
    "id": "nier-automata",
    "familyId": "nier-automata",
    "label": "NieR: Automata",
    "official": false,
    "appearance": "light",
    "tokens": {
      "appearance": "light",
      "bg": "#ccc8b1",
      "bgRaised": "#d1cdb7",
      "bgHover": "#b8b49d",
      "surface": "#c6c2ab",
      "border": "#a29e8961",
      "borderStrong": "#a29e8994",
      "text": "#211f1b",
      "muted": "#4d4b3f",
      "accent": "#211f1b",
      "onAccent": "#ffffff",
      "accent2": "#211f1b",
      "accentSoft": "#211f1b29",
      "attention": "#a08e42",
      "attentionRing": "#a08e424d",
      "ok": "#211f1b",
      "danger": "#a94a38",
      "termBg": "#ccc8b1",
      "termFg": "#211f1b",
      "termCursor": "#211f1b",
      "termSelection": "#aeaa93",
      "termChrome": "#ccc8b1",
      "termChromeText": "#211f1b",
      "termChromeMuted": "#4d4b3f",
      "preview": [
        "#ccc8b1",
        "#c6c2ab",
        "#211f1b",
        "#211f1b"
      ]
    },
    "ansi": {
      "black": "#ccc8b1",
      "red": "#a94a38",
      "green": "#211f1b",
      "yellow": "#a08e42",
      "blue": "#211f1b",
      "magenta": "#211f1b",
      "cyan": "#211f1b",
      "white": "#211f1b",
      "brightBlack": "#4d4b3f",
      "brightRed": "#a94a38",
      "brightGreen": "#211f1b",
      "brightYellow": "#a08e42",
      "brightBlue": "#211f1b",
      "brightMagenta": "#211f1b",
      "brightCyan": "#211f1b",
      "brightWhite": "#020617"
    }
  },
  {
    "id": "nier-automata-dark",
    "familyId": "nier-automata",
    "label": "NieR: Automata",
    "official": false,
    "appearance": "dark",
    "tokens": {
      "appearance": "dark",
      "bg": "#2f2d26",
      "bgRaised": "#3b3930",
      "bgHover": "#33312a",
      "surface": "#36342c",
      "border": "#4f4d4524",
      "borderStrong": "#4f4d453d",
      "text": "#d1cdb7",
      "muted": "#a8a593",
      "accent": "#d1cdb7",
      "onAccent": "#2f2d26",
      "accent2": "#b5b096",
      "accentSoft": "#d1cdb729",
      "attention": "#c2b169",
      "attentionRing": "#c2b1694d",
      "ok": "#b5b096",
      "danger": "#c96b57",
      "termBg": "#2b2923",
      "termFg": "#d1cdb7",
      "termCursor": "#d1cdb7",
      "termSelection": "#45433a",
      "termChrome": "#2f2d26",
      "termChromeText": "#d1cdb7",
      "termChromeMuted": "#9d9986",
      "preview": [
        "#2f2d26",
        "#36342c",
        "#d1cdb7",
        "#d1cdb7"
      ]
    },
    "ansi": {
      "black": "#2b2923",
      "red": "#c96b57",
      "green": "#b5b096",
      "yellow": "#c2b169",
      "blue": "#d1cdb7",
      "magenta": "#b5b096",
      "cyan": "#b5b096",
      "white": "#d1cdb7",
      "brightBlack": "#a8a593",
      "brightRed": "#c96b57",
      "brightGreen": "#b5b096",
      "brightYellow": "#c2b169",
      "brightBlue": "#d1cdb7",
      "brightMagenta": "#b5b096",
      "brightCyan": "#b5b096",
      "brightWhite": "#ffffff"
    }
  },
  {
    "id": "one-dark-pro-night-flat",
    "familyId": "one-dark-pro-night-flat",
    "label": "One Dark Pro",
    "official": false,
    "appearance": "dark",
    "tokens": {
      "appearance": "dark",
      "bg": "#16191d",
      "bgRaised": "#23272e",
      "bgHover": "#2c313a",
      "surface": "#1e2227",
      "border": "#3e445224",
      "borderStrong": "#3e44523d",
      "text": "#abb2bf",
      "muted": "#6c7482",
      "accent": "#4d78cc",
      "onAccent": "#ffffff",
      "accent2": "#98c379",
      "accentSoft": "#4d78cc29",
      "attention": "#d19a66",
      "attentionRing": "#d19a664d",
      "ok": "#98c379",
      "danger": "#c24038",
      "termBg": "#16191d",
      "termFg": "#abb2bf",
      "termCursor": "#528bff",
      "termSelection": "#3e4452",
      "termChrome": "#16191d",
      "termChromeText": "#abb2bf",
      "termChromeMuted": "#5c6370",
      "preview": [
        "#16191d",
        "#1e2227",
        "#4d78cc",
        "#abb2bf"
      ]
    },
    "ansi": {
      "black": "#16191d",
      "red": "#c24038",
      "green": "#98c379",
      "yellow": "#d19a66",
      "blue": "#4d78cc",
      "magenta": "#98c379",
      "cyan": "#98c379",
      "white": "#abb2bf",
      "brightBlack": "#6c7482",
      "brightRed": "#c24038",
      "brightGreen": "#98c379",
      "brightYellow": "#d19a66",
      "brightBlue": "#4d78cc",
      "brightMagenta": "#98c379",
      "brightCyan": "#98c379",
      "brightWhite": "#ffffff"
    }
  },
  {
    "id": "one-dark-pro-night-flat-light",
    "familyId": "one-dark-pro-night-flat",
    "label": "One Dark Pro",
    "official": false,
    "appearance": "light",
    "tokens": {
      "appearance": "light",
      "bg": "#fafafa",
      "bgRaised": "#f0f0f1",
      "bgHover": "#e8e8e9",
      "surface": "#ffffff",
      "border": "#e5e5e661",
      "borderStrong": "#e5e5e694",
      "text": "#383a42",
      "muted": "#a0a1a7",
      "accent": "#4078f2",
      "onAccent": "#ffffff",
      "accent2": "#50a14f",
      "accentSoft": "#4078f229",
      "attention": "#c18401",
      "attentionRing": "#c184014d",
      "ok": "#50a14f",
      "danger": "#e45649",
      "termBg": "#fafafa",
      "termFg": "#383a42",
      "termCursor": "#4078f2",
      "termSelection": "#d0d7de",
      "termChrome": "#fafafa",
      "termChromeText": "#383a42",
      "termChromeMuted": "#a0a1a7",
      "preview": [
        "#fafafa",
        "#ffffff",
        "#4078f2",
        "#383a42"
      ]
    },
    "ansi": {
      "black": "#fafafa",
      "red": "#e45649",
      "green": "#50a14f",
      "yellow": "#c18401",
      "blue": "#4078f2",
      "magenta": "#50a14f",
      "cyan": "#50a14f",
      "white": "#383a42",
      "brightBlack": "#a0a1a7",
      "brightRed": "#e45649",
      "brightGreen": "#50a14f",
      "brightYellow": "#c18401",
      "brightBlue": "#4078f2",
      "brightMagenta": "#50a14f",
      "brightCyan": "#50a14f",
      "brightWhite": "#020617"
    }
  },
  {
    "id": "paper-ember",
    "familyId": "paper-ember",
    "label": "Paper Ember",
    "official": false,
    "appearance": "light",
    "tokens": {
      "appearance": "light",
      "bg": "#faf6f0",
      "bgRaised": "#fdfaf5",
      "bgHover": "#fdfaf5",
      "surface": "#f4eee5",
      "border": "#e7ddd061",
      "borderStrong": "#e7ddd094",
      "text": "#44403c",
      "muted": "#8a817a",
      "accent": "#c2571f",
      "onAccent": "#ffffff",
      "accent2": "#07090e",
      "accentSoft": "#c2571f29",
      "attention": "#efc35a",
      "attentionRing": "#efc35a4d",
      "ok": "#07090e",
      "danger": "#ff7b7b",
      "termBg": "#faf6f0",
      "termFg": "#44403c",
      "termCursor": "#c2571f",
      "termSelection": "#ecd9c3",
      "termChrome": "#faf6f0",
      "termChromeText": "#44403c",
      "termChromeMuted": "#8a817a",
      "preview": [
        "#faf6f0",
        "#f4eee5",
        "#c2571f",
        "#44403c"
      ]
    },
    "ansi": {
      "black": "#faf6f0",
      "red": "#ff7b7b",
      "green": "#07090e",
      "yellow": "#efc35a",
      "blue": "#c2571f",
      "magenta": "#07090e",
      "cyan": "#07090e",
      "white": "#44403c",
      "brightBlack": "#8a817a",
      "brightRed": "#ff7b7b",
      "brightGreen": "#07090e",
      "brightYellow": "#efc35a",
      "brightBlue": "#c2571f",
      "brightMagenta": "#07090e",
      "brightCyan": "#07090e",
      "brightWhite": "#020617"
    }
  },
  {
    "id": "paper-ember-dark",
    "familyId": "paper-ember",
    "label": "Paper Ember",
    "official": false,
    "appearance": "dark",
    "tokens": {
      "appearance": "dark",
      "bg": "#1c1917",
      "bgRaised": "#2a2725",
      "bgHover": "#2a2725",
      "surface": "#242120",
      "border": "#33302c24",
      "borderStrong": "#33302c3d",
      "text": "#e7e5e4",
      "muted": "#a8a29e",
      "accent": "#ea884b",
      "onAccent": "#ffffff",
      "accent2": "#ea884b",
      "accentSoft": "#ea884b29",
      "attention": "#efc35a",
      "attentionRing": "#efc35a4d",
      "ok": "#07090e",
      "danger": "#ff7b7b",
      "termBg": "#1c1917",
      "termFg": "#e7e5e4",
      "termCursor": "#ea884b",
      "termSelection": "#443528",
      "termChrome": "#1c1917",
      "termChromeText": "#e7e5e4",
      "termChromeMuted": "#a8a29e",
      "preview": [
        "#1c1917",
        "#242120",
        "#ea884b",
        "#e7e5e4"
      ]
    },
    "ansi": {
      "black": "#1c1917",
      "red": "#ff7b7b",
      "green": "#07090e",
      "yellow": "#efc35a",
      "blue": "#ea884b",
      "magenta": "#ea884b",
      "cyan": "#ea884b",
      "white": "#e7e5e4",
      "brightBlack": "#a8a29e",
      "brightRed": "#ff7b7b",
      "brightGreen": "#07090e",
      "brightYellow": "#efc35a",
      "brightBlue": "#ea884b",
      "brightMagenta": "#ea884b",
      "brightCyan": "#ea884b",
      "brightWhite": "#ffffff"
    }
  },
  {
    "id": "phosphor",
    "familyId": "phosphor",
    "label": "Phosphor",
    "official": false,
    "appearance": "dark",
    "tokens": {
      "appearance": "dark",
      "bg": "#060b06",
      "bgRaised": "#101c12",
      "bgHover": "#1c3322",
      "surface": "#0b140c",
      "border": "#1c332224",
      "borderStrong": "#1c33223d",
      "text": "#a5efb7",
      "muted": "#549a67",
      "accent": "#3dff7c",
      "onAccent": "#04140a",
      "accent2": "#3dff7c",
      "accentSoft": "#3dff7c29",
      "attention": "#efc35a",
      "attentionRing": "#efc35a4d",
      "ok": "#07090e",
      "danger": "#ff7b7b",
      "termBg": "#050a05",
      "termFg": "#a5efb7",
      "termCursor": "#3dff7c",
      "termSelection": "#17402a",
      "termChrome": "#060b06",
      "termChromeText": "#8fe6a5",
      "termChromeMuted": "#4d8c5e",
      "preview": [
        "#060b06",
        "#0b140c",
        "#3dff7c",
        "#a5efb7"
      ]
    },
    "ansi": {
      "black": "#050a05",
      "red": "#ff7b7b",
      "green": "#07090e",
      "yellow": "#efc35a",
      "blue": "#3dff7c",
      "magenta": "#3dff7c",
      "cyan": "#3dff7c",
      "white": "#a5efb7",
      "brightBlack": "#549a67",
      "brightRed": "#ff7b7b",
      "brightGreen": "#07090e",
      "brightYellow": "#efc35a",
      "brightBlue": "#3dff7c",
      "brightMagenta": "#3dff7c",
      "brightCyan": "#3dff7c",
      "brightWhite": "#ffffff"
    }
  },
  {
    "id": "poimandres-dark-theme",
    "familyId": "poimandres-dark-theme",
    "label": "Poimandres",
    "official": false,
    "appearance": "dark",
    "tokens": {
      "appearance": "dark",
      "bg": "#1b1e28",
      "bgRaised": "#1b1e28",
      "bgHover": "#262934",
      "surface": "#1b1e28",
      "border": "#3a3e4d24",
      "borderStrong": "#3a3e4d3d",
      "text": "#bfc3db",
      "muted": "#8c8e94",
      "accent": "#89ddff",
      "onAccent": "#ffffff",
      "accent2": "#89ddff",
      "accentSoft": "#89ddff29",
      "attention": "#fffac2",
      "attentionRing": "#fffac24d",
      "ok": "#3fd49a",
      "danger": "#d0679d",
      "termBg": "#1b1e28",
      "termFg": "#a6accd",
      "termCursor": "#a6accd",
      "termSelection": "#272c3c",
      "termChrome": "#1b1e28",
      "termChromeText": "#edeef1",
      "termChromeMuted": "#97999d",
      "preview": [
        "#1b1e28",
        "#1b1e28",
        "#89ddff",
        "#bfc3db"
      ]
    },
    "ansi": {
      "black": "#1b1e28",
      "red": "#d0679d",
      "green": "#3fd49a",
      "yellow": "#fffac2",
      "blue": "#89ddff",
      "magenta": "#89ddff",
      "cyan": "#89ddff",
      "white": "#a6accd",
      "brightBlack": "#8c8e94",
      "brightRed": "#d0679d",
      "brightGreen": "#3fd49a",
      "brightYellow": "#fffac2",
      "brightBlue": "#89ddff",
      "brightMagenta": "#89ddff",
      "brightCyan": "#89ddff",
      "brightWhite": "#ffffff"
    }
  },
  {
    "id": "rose-pine-dawn",
    "familyId": "rose-pine-dawn",
    "label": "Rosé Pine Dawn",
    "official": false,
    "appearance": "light",
    "tokens": {
      "appearance": "light",
      "bg": "#faf4ed",
      "bgRaised": "#ffffff",
      "bgHover": "#c8dfe8",
      "surface": "#ffffff",
      "border": "#e8e2d961",
      "borderStrong": "#e8e2d994",
      "text": "#27272a",
      "muted": "#71717b",
      "accent": "#286983",
      "onAccent": "#ffffff",
      "accent2": "#1b4ed8",
      "accentSoft": "#28698329",
      "attention": "#fe9a00",
      "attentionRing": "#fe9a004d",
      "ok": "#15803d",
      "danger": "#fb2c36",
      "termBg": "#faf4ed",
      "termFg": "#27272a",
      "termCursor": "#286983",
      "termSelection": "#afffff33",
      "termChrome": "#faf4ed",
      "termChromeText": "#27272a",
      "termChromeMuted": "#55808f",
      "preview": [
        "#faf4ed",
        "#ffffff",
        "#286983",
        "#27272a"
      ]
    },
    "ansi": {
      "black": "#faf4ed",
      "red": "#fb2c36",
      "green": "#15803d",
      "yellow": "#fe9a00",
      "blue": "#286983",
      "magenta": "#1b4ed8",
      "cyan": "#1b4ed8",
      "white": "#27272a",
      "brightBlack": "#71717b",
      "brightRed": "#fb2c36",
      "brightGreen": "#15803d",
      "brightYellow": "#fe9a00",
      "brightBlue": "#286983",
      "brightMagenta": "#1b4ed8",
      "brightCyan": "#1b4ed8",
      "brightWhite": "#020617"
    }
  },
  {
    "id": "sakura",
    "familyId": "sakura",
    "label": "Sakura",
    "official": false,
    "appearance": "light",
    "tokens": {
      "appearance": "light",
      "bg": "#fbf3f5",
      "bgRaised": "#fdf7f9",
      "bgHover": "#ecd7de",
      "surface": "#f6ebee",
      "border": "#ecd7de61",
      "borderStrong": "#ecd7de94",
      "text": "#432b36",
      "muted": "#8a6675",
      "accent": "#b83d72",
      "onAccent": "#ffffff",
      "accent2": "#07090e",
      "accentSoft": "#b83d7229",
      "attention": "#efc35a",
      "attentionRing": "#efc35a4d",
      "ok": "#07090e",
      "danger": "#ff7b7b",
      "termBg": "#fbf3f5",
      "termFg": "#432b36",
      "termCursor": "#b83d72",
      "termSelection": "#e9cdd8",
      "termChrome": "#fbf3f5",
      "termChromeText": "#432b36",
      "termChromeMuted": "#8a6675",
      "preview": [
        "#fbf3f5",
        "#f6ebee",
        "#b83d72",
        "#432b36"
      ]
    },
    "ansi": {
      "black": "#fbf3f5",
      "red": "#ff7b7b",
      "green": "#07090e",
      "yellow": "#efc35a",
      "blue": "#b83d72",
      "magenta": "#07090e",
      "cyan": "#07090e",
      "white": "#432b36",
      "brightBlack": "#8a6675",
      "brightRed": "#ff7b7b",
      "brightGreen": "#07090e",
      "brightYellow": "#efc35a",
      "brightBlue": "#b83d72",
      "brightMagenta": "#07090e",
      "brightCyan": "#07090e",
      "brightWhite": "#020617"
    }
  },
  {
    "id": "sakura-dark",
    "familyId": "sakura",
    "label": "Sakura",
    "official": false,
    "appearance": "dark",
    "tokens": {
      "appearance": "dark",
      "bg": "#241820",
      "bgRaised": "#33232f",
      "bgHover": "#3c2a36",
      "surface": "#2c1e28",
      "border": "#3c2a3624",
      "borderStrong": "#3c2a363d",
      "text": "#eedbe4",
      "muted": "#b18ea0",
      "accent": "#e88fb4",
      "onAccent": "#ffffff",
      "accent2": "#e88fb4",
      "accentSoft": "#e88fb429",
      "attention": "#efc35a",
      "attentionRing": "#efc35a4d",
      "ok": "#07090e",
      "danger": "#ff7b7b",
      "termBg": "#20151d",
      "termFg": "#eedbe4",
      "termCursor": "#e88fb4",
      "termSelection": "#45303e",
      "termChrome": "#241820",
      "termChromeText": "#eedbe4",
      "termChromeMuted": "#a7859a",
      "preview": [
        "#241820",
        "#2c1e28",
        "#e88fb4",
        "#eedbe4"
      ]
    },
    "ansi": {
      "black": "#20151d",
      "red": "#ff7b7b",
      "green": "#07090e",
      "yellow": "#efc35a",
      "blue": "#e88fb4",
      "magenta": "#e88fb4",
      "cyan": "#e88fb4",
      "white": "#eedbe4",
      "brightBlack": "#b18ea0",
      "brightRed": "#ff7b7b",
      "brightGreen": "#07090e",
      "brightYellow": "#efc35a",
      "brightBlue": "#e88fb4",
      "brightMagenta": "#e88fb4",
      "brightCyan": "#e88fb4",
      "brightWhite": "#ffffff"
    }
  },
  {
    "id": "whirl",
    "familyId": "whirl",
    "label": "Whirl",
    "official": false,
    "appearance": "dark",
    "tokens": {
      "appearance": "dark",
      "bg": "#131313",
      "bgRaised": "#252526",
      "bgHover": "#1e1e1f",
      "surface": "#1c1c1c",
      "border": "#2a2a2b24",
      "borderStrong": "#2a2a2b3d",
      "text": "#f0f0f0",
      "muted": "#888888",
      "accent": "#dedede",
      "onAccent": "#161616",
      "accent2": "#3987e5",
      "accentSoft": "#dedede29",
      "attention": "#f5a524",
      "attentionRing": "#f5a5244d",
      "ok": "#3fd49a",
      "danger": "#ff6467",
      "termBg": "#131313",
      "termFg": "#e8e8e8",
      "termCursor": "#f0f0f0",
      "termSelection": "#ffffff2e",
      "termChrome": "#131313",
      "termChromeText": "#b7b7b7",
      "termChromeMuted": "#7d7d7d",
      "preview": [
        "#131313",
        "#1c1c1c",
        "#dedede",
        "#f0f0f0"
      ]
    },
    "ansi": {
      "black": "#131313",
      "red": "#ff6467",
      "green": "#3fd49a",
      "yellow": "#f5a524",
      "blue": "#dedede",
      "magenta": "#3987e5",
      "cyan": "#3987e5",
      "white": "#e8e8e8",
      "brightBlack": "#888888",
      "brightRed": "#ff6467",
      "brightGreen": "#3fd49a",
      "brightYellow": "#f5a524",
      "brightBlue": "#dedede",
      "brightMagenta": "#3987e5",
      "brightCyan": "#3987e5",
      "brightWhite": "#ffffff"
    }
  },
  {
    "id": "whirl-light",
    "familyId": "whirl",
    "label": "Whirl",
    "official": false,
    "appearance": "light",
    "tokens": {
      "appearance": "light",
      "bg": "#f3f3f4",
      "bgRaised": "#ffffff",
      "bgHover": "#f8f8f9",
      "surface": "#ffffff",
      "border": "#dcdcdd61",
      "borderStrong": "#dcdcdd94",
      "text": "#141414",
      "muted": "#696969",
      "accent": "#0f0f0f",
      "onAccent": "#ffffff",
      "accent2": "#1c6fca",
      "accentSoft": "#0f0f0f29",
      "attention": "#b45309",
      "attentionRing": "#b453094d",
      "ok": "#1c6fca",
      "danger": "#e7000b",
      "termBg": "#fbfbfc",
      "termFg": "#1f1f1f",
      "termCursor": "#141414",
      "termSelection": "#1414141f",
      "termChrome": "#f3f3f4",
      "termChromeText": "#555555",
      "termChromeMuted": "#767678",
      "preview": [
        "#f3f3f4",
        "#ffffff",
        "#0f0f0f",
        "#141414"
      ]
    },
    "ansi": {
      "black": "#fbfbfc",
      "red": "#e7000b",
      "green": "#1c6fca",
      "yellow": "#b45309",
      "blue": "#0f0f0f",
      "magenta": "#1c6fca",
      "cyan": "#1c6fca",
      "white": "#1f1f1f",
      "brightBlack": "#696969",
      "brightRed": "#e7000b",
      "brightGreen": "#1c6fca",
      "brightYellow": "#b45309",
      "brightBlue": "#0f0f0f",
      "brightMagenta": "#1c6fca",
      "brightCyan": "#1c6fca",
      "brightWhite": "#020617"
    }
  }
];

export const THEME_IDS = THEME_CATALOG.map((t) => t.id);

export type ThemeId = (typeof THEME_CATALOG)[number]["id"] | "default";

export function getTheme(id: string): ThemeDefinition {
  const key = id === "default" ? "voxiva" : id;
  return THEME_CATALOG.find((t) => t.id === key) ?? THEME_CATALOG[0];
}

/** Old Space theme ids → catalog. */
const LEGACY: Record<string, string> = {
  default: "voxiva",
  glass: "voxiva",
  gruvbox: "espresso",
  cyber: "miami-nights",
  dark: "whirl",
  light: "rose-pine-dawn",
};

export function resolveThemeId(id: string | null | undefined): ThemeId {
  if (!id) return "voxiva";
  const mapped = LEGACY[id] ?? id;
  return (THEME_IDS.includes(mapped) ? mapped : "voxiva") as ThemeId;
}
